// Package proto provides the Go type definitions for the SecurityScarletAI
// gRPC protocol. These types mirror the protobuf definitions in
// securityscarlet.proto (SRD Section 11.5).
//
// When protoc is available, these hand-written types can be replaced with
// generated code:
//
//	protoc --go_out=. --go-grpc_out=. securityscarlet.proto
//
// Until then, these types provide the same interface for the gRPC client.
package proto

import (
	"context"
	"fmt"
	"io"
	"log"
	"sync"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"
)

// ── gRPC Service Name ──────────────────────────────────────────────────

// ServiceName is the gRPC service name for health checking.
const ServiceName = "securityscarlet.ai.v1.SecurityScarletAI"

// ── Message Types ──────────────────────────────────────────────────────

// SecurityEvent represents a single security event for AI analysis.
// Mirrors the protobuf message SecurityEvent from securityscarlet.proto.
type SecurityEvent struct {
	TimestampNS  uint64
	PID          uint32
	PPID         uint32
	UID          uint32
	GID         uint32
	Category    uint32
	EventType   uint32
	SyscallNr   uint32
	Comm        string
	ContainerID string
	ContainerImage string
	Namespace   string

	// Oneof payload (only one should be set based on Category)
	ProcessPayload  *ProcessPayload
	FilePayload      *FilePayload
	NetworkPayload   *NetworkPayload
	EscapePayload    *EscapePayload
	PrivilegePayload *PrivilegePayload
}

// ProcessPayload holds process-specific event data.
type ProcessPayload struct {
	Filename string
	Args     string
}

// FilePayload holds file-specific event data.
type FilePayload struct {
	Path  string
	Flags uint32
	Mode  uint32
}

// NetworkPayload holds network-specific event data.
type NetworkPayload struct {
	RemoteAddr []byte
	LocalAddr  []byte
	RemotePort uint32
	LocalPort  uint32
	Protocol   uint32
}

// EscapePayload holds container escape event data.
type EscapePayload struct {
	NSType   uint32
	TargetNS []uint32
}

// PrivilegePayload holds privilege escalation event data.
type PrivilegePayload struct {
	OldUID    uint32
	NewUID    uint32
	Capability uint32
	ModeFlags  uint32
}

// AnalysisResult is the result of AI event analysis.
type AnalysisResult struct {
	AnomalyScore      float64
	Classification    string
	Description      string
	EnforceRecommended bool
	Confidence       float64
	ModelVersion     string
}

// ProfileRequest asks the AI service for a behavioral profile.
type ProfileRequest struct {
	Image        string
	ForceRebuild bool
}

// BehavioralProfile contains a per-image behavioral baseline.
type BehavioralProfile struct {
	Image          string
	SyscallProfile *SyscallProfile
	NetworkProfile *NetworkProfile
	FileProfile    *FileProfile
	BaselineEvents uint64
	Confidence     float64
}

// SyscallProfile describes expected syscall patterns.
type SyscallProfile struct {
	TopSyscalls       map[string]float64
	UniqueSyscallCount int
	NgramHashes       []uint64
}

// NetworkProfile describes expected network behavior.
type NetworkProfile struct {
	ExpectedPorts    map[uint32]float64
	ExpectedProtocols map[string]float64
	ConnectionRate   float64
}

// FileProfile describes expected file access patterns.
type FileProfile struct {
	ReadPaths     []string
	WritePaths    []string
	DriftBaseline []string
}

// Alert represents a security alert submitted for triage.
type Alert struct {
	RuleID        string
	Priority      string
	Namespace     string
	Container     string
	Output        string
	ProcessName   string
	PID           uint32
	ContainerImage string
}

// TriageResult is the AI assessment of an alert's validity.
type TriageResult struct {
	FalsePositiveScore float64
	Priority           string
	Reasoning          string
	SuppressRecommended bool
	Confidence         float64
}

// IncidentContext provides context for AI rule suggestion.
type IncidentContext struct {
	RuleID        string
	Events        []IncidentEvent
	ContainerImage string
	Namespace     string
	TimestampNS   uint64
}

// IncidentEvent is a simplified event in the incident context.
type IncidentEvent struct {
	EventType  string
	ProcessName string
	PID        uint32
	Category   string
	TimestampNS uint64
	Details    map[string]string
}

// RuleSuggestion is a draft YAML rule generated by the AI.
type RuleSuggestion struct {
	RuleYAML        string
	Reasoning       string
	BasedOnIncidents int
	Confidence       float64
	Status           string // "draft", "pending_approval", "approved", "rejected"
}

// ── gRPC Client ────────────────────────────────────────────────────────

// SecurityScarletAIClient is the client API for the SecurityScarletAI gRPC service.
// When the server is unavailable, all methods return gracefully degraded results.
type SecurityScarletAIClient struct {
	mu sync.RWMutex

	// gRPC connection
	conn    *grpc.ClientConn
	healthClient grpc_health_v1.HealthClient

	// Configuration
	endpoint string
	timeout  time.Duration

	// State
	connected bool
	healthy   bool
}

// NewSecurityScarletAIClient creates a new gRPC client for the AI service.
func NewSecurityScarletAIClient(endpoint string, timeout time.Duration) *SecurityScarletAIClient {
	if timeout <= 0 {
		timeout = 5 * time.Second
	}
	return &SecurityScarletAIClient{
		endpoint: endpoint,
		timeout:  timeout,
	}
}

// Connect establishes a gRPC connection to the SecurityScarletAI service.
func (c *SecurityScarletAIClient) Connect(ctx context.Context) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.connected {
		return nil
	}

	opts := []grpc.DialOption{
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
	}

	// Apply timeout
	connectCtx, cancel := context.WithTimeout(ctx, c.timeout)
	defer cancel()

	conn, err := grpc.DialContext(connectCtx, c.endpoint, opts...)
	if err != nil {
		return fmt.Errorf("gRPC connection to %s failed: %w", c.endpoint, err)
	}

	c.conn = conn
	c.healthClient = grpc_health_v1.NewHealthClient(conn)
	c.connected = true

	log.Printf("[ai/proto] Connected to SecurityScarletAI at %s", c.endpoint)
	return nil
}

// Disconnect closes the gRPC connection.
func (c *SecurityScarletAIClient) Disconnect() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if !c.connected || c.conn == nil {
		return nil
	}

	err := c.conn.Close()
	c.connected = false
	c.healthy = false
	c.conn = nil

	log.Printf("[ai/proto] Disconnected from SecurityScarletAI")
	return err
}

// IsConnected returns whether the gRPC connection is active.
func (c *SecurityScarletAIClient) IsConnected() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.connected
}

// CheckHealth checks the health of the AI service via gRPC health checking.
func (c *SecurityScarletAIClient) CheckHealth(ctx context.Context) (bool, error) {
	c.mu.RLock()
	hc := c.healthClient
	c.mu.RUnlock()

	if hc == nil {
		return false, fmt.Errorf("not connected")
	}

	healthCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()

	resp, err := hc.Check(healthCtx, &grpc_health_v1.HealthCheckRequest{
		Service: ServiceName,
	})
	if err != nil {
		c.mu.Lock()
		c.healthy = false
		c.mu.Unlock()
		return false, fmt.Errorf("health check failed: %w", err)
	}

	healthy := resp.GetStatus() == grpc_health_v1.HealthCheckResponse_SERVING
	c.mu.Lock()
	c.healthy = healthy
	c.mu.Unlock()
	return healthy, nil
}

// ── gRPC RPC Stubs ───────────────────────────────────────────────────

// AnalyzeEvents sends an event to the AI service for analysis.
// When the service is unavailable, returns a neutral result.
func (c *SecurityScarletAIClient) AnalyzeEvents(ctx context.Context, event *SecurityEvent) (*AnalysisResult, error) {
	c.mu.RLock()
	connected := c.connected
	c.mu.RUnlock()

	if !connected {
		return &AnalysisResult{
			AnomalyScore:      0.0,
			Classification:    "unknown",
			Description:       "AI service not connected",
			EnforceRecommended: false,
			Confidence:        0.0,
		}, nil
	}

	// TODO: When protobuf-generated client stubs are available:
	//   stream, err := c.client.AnalyzeEvents(ctx)
	//   if err != nil { return nil, err }
	//   if err := stream.Send(eventToProto(event)); err != nil { return nil, err }
	//   result, err := stream.Recv()
	//   if err != nil { return nil, err }
	//   return protoToAnalysisResult(result), nil

	// Stub: returns neutral result while gRPC service is not yet deployed
	return &AnalysisResult{
		AnomalyScore:      0.0,
		Classification:    "unknown",
		Description:       "gRPC AnalyzeEvents stub (protobuf code generation pending)",
		EnforceRecommended: false,
		Confidence:        0.0,
		ModelVersion:      "stub-v0",
	}, nil
}

// GetProfile requests a behavioral profile for a container image.
func (c *SecurityScarletAIClient) GetProfile(ctx context.Context, req *ProfileRequest) (*BehavioralProfile, error) {
	c.mu.RLock()
	connected := c.connected
	c.mu.RUnlock()

	if !connected {
		return &BehavioralProfile{
			Image:      req.Image,
			Confidence: 0.0,
		}, nil
	}

	// TODO: When protobuf-generated client stubs are available:
	//   profile, err := c.client.GetProfile(ctx, profileRequestToProto(req))
	//   if err != nil { return nil, err }
	//   return protoToBehavioralProfile(profile), nil

	return &BehavioralProfile{
		Image:          req.Image,
		BaselineEvents: 0,
		Confidence:     0.0,
	}, nil
}

// TriageAlert submits an alert for false-positive assessment.
func (c *SecurityScarletAIClient) TriageAlert(ctx context.Context, alert *Alert) (*TriageResult, error) {
	c.mu.RLock()
	connected := c.connected
	c.mu.RUnlock()

	if !connected {
		return &TriageResult{
			FalsePositiveScore: 0.5, // neutral
			Priority:           alert.Priority,
			Confidence:         0.0,
		}, nil
	}

	// TODO: When protobuf-generated client stubs are available:
	//   result, err := c.client.TriageAlert(ctx, alertToProto(alert))
	//   if err != nil { return nil, err }
	//   return protoToTriageResult(result), nil

	return &TriageResult{
		FalsePositiveScore: 0.5,
		Priority:          alert.Priority,
		Confidence:        0.0,
		Reasoning:        "gRPC TriageAlert stub",
	}, nil
}

// SuggestRule requests an AI-generated rule suggestion from incident context.
func (c *SecurityScarletAIClient) SuggestRule(ctx context.Context, incident *IncidentContext) (*RuleSuggestion, error) {
	c.mu.RLock()
	connected := c.connected
	c.mu.RUnlock()

	if !connected {
		return nil, fmt.Errorf("AI service not connected for rule suggestion")
	}

	// TODO: When protobuf-generated client stubs are available:
	//   suggestion, err := c.client.SuggestRule(ctx, incidentToProto(incident))
	//   if err != nil { return nil, err }
	//   return protoToRuleSuggestion(suggestion), nil

	return &RuleSuggestion{
		RuleYAML:        "# AI-suggested rule placeholder (gRPC SuggestRule stub)",
		Reasoning:       fmt.Sprintf("Based on %d incidents related to %s", len(incident.Events), incident.RuleID),
		BasedOnIncidents: len(incident.Events),
		Confidence:       0.0,
		Status:          "draft",
	}, nil
}

// ── gRPC Server ─────────────────────────────────────────────────────────

// SecurityScarletAIServer is the server API for the SecurityScarletAI service.
// This is intended to be implemented by the AI inference service, not the
// runtime agent. Provided here for reference and testing.
// When protobuf code generation is available, this will be replaced with
// the generated UnimplementedSecurityScarletAIServer.
type SecurityScarletAIServer interface {
	// AnalyzeEvents processes a stream of security events and returns analysis results.
	// The stream is bidirectional: events flow in, analysis results flow out.
	AnalyzeEvents(ctx context.Context, events <-chan *SecurityEvent, results chan<- *AnalysisResult) error
	GetProfile(context.Context, *ProfileRequest) (*BehavioralProfile, error)
	TriageAlert(context.Context, *Alert) (*TriageResult, error)
	SuggestRule(context.Context, *IncidentContext) (*RuleSuggestion, error)
}

// ── Helper: stream wrappers ─────────────────────────────────────────────

// SecurityEventStream wraps a gRPC stream for AnalyzeEvents.
type SecurityEventStream interface {
	Send(event *SecurityEvent) error
	Recv() (*AnalysisResult, error)
	Close() error
}

// eventStream is a bidirectional stream stub for testing.
type eventStream struct {
	events chan *SecurityEvent
	results chan *AnalysisResult
	closed bool
	mu     sync.Mutex
}

// NewEventStream creates a new bidirectional event stream for testing.
func NewEventStream() *eventStream {
	return &eventStream{
		events:  make(chan *SecurityEvent, 100),
		results: make(chan *AnalysisResult, 100),
	}
}

func (s *eventStream) Send(event *SecurityEvent) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return io.EOF
	}
	s.events <- event
	return nil
}

func (s *eventStream) Recv() (*AnalysisResult, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return nil, io.EOF
	}
	select {
	case result := <-s.results:
		return result, nil
	default:
		return &AnalysisResult{Classification: "unknown"}, nil
	}
}

func (s *eventStream) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.closed = true
	return nil
}

// ── Health Server ──────────────────────────────────────────────────────

// RegisterHealthServer registers the gRPC health server on the given
// gRPC server. This enables health checking for the AI service.
func RegisterHealthServer(s *grpc.Server) {
	healthServer := health.NewServer()
	healthServer.SetServingStatus(ServiceName, grpc_health_v1.HealthCheckResponse_SERVING)
	grpc_health_v1.RegisterHealthServer(s, healthServer)
}